#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

PUID=${PUID:-1099}
PGID=${PGID:-1099}
PNAME=${PNAME:-bob}
PHOME=${PHOME:-"/home/${PNAME}"}
VNC_PASSWORD=${VNC_PASSWORD:-$(echo $RANDOM | md5sum | head -c 20; echo;)}
PKGS=${PKGS:-}

id "${PNAME}" &>/dev/null || ( \
  groupadd \
    --gid "$PGID" \
    "${PNAME}" && \
  useradd \
    --home-dir "${PHOME}" \
    --create-home \
    --gid "${PNAME}" \
    --uid "${PUID}" \
    --shell "/bin/bash" \
    "${PNAME}" \
  )

echo "User -> $PNAME(uid:$(id -u "${PNAME}"), gid:$(id -g "${PNAME}"))"

mkdir -p "${PHOME}/.vnc" 

rm -f "${PHOME}/.vnc/passwd" && vncpasswd -f <<< "${VNC_PASSWORD}" > "${PHOME}/.vnc/passwd"
chmod 600 "${PHOME}/.vnc/passwd"
chown -R "${PNAME}:${PNAME}" "${PHOME}/.vnc"

if [ "${PKGS}" != "" ]; then
  apt-get update
  echo "${PKGS}" | xargs apt-get install -y
fi

sudo -E -u "${PNAME}" /start-vnc.sh